ldc return fix
Error: 'return' can only be used with 'ref' or 'out'

Dmd compiles fine with return, but ldc requires it to be ref or out.
Removed returns, it's more a compiler hint anyways. They can easily be
added in later, but aren't neccesary for the code to work.